### ISSUE TITLE
This Is Error In My TERMINAL

### ISSUE THREAD

**Issue by swayam-crypto** [ZerioDev/Giveaway-bot#13]
C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\bindings\bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\build\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\build\Release\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\out\Debug\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\Debug\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\out\Release\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\Release\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\build\default\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\compiled\14.16.0\win32\x64\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\addon-build\release\install-root\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\addon-build\debug\install-root\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\addon-build\default\install-root\better_sqlite3.node
 → C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\lib\binding\node-v83-win32-x64\better_sqlite3.node
    at bindings (C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\lib\database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\dell\Desktop\Giveaway-bot-master\node_modules\quick.db\node_modules\better-sqlite3\lib\index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\build\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\build\\Debug\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\build\\Release\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\out\\Debug\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\Debug\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\out\\Release\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\Release\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\build\\default\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\compiled\\14.16.0\\win32\\x64\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\addon-build\\release\\install-root\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\addon-build\\debug\\install-root\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\addon-build\\default\\install-root\\better_sqlite3.node',
    'C:\\Users\\dell\\Desktop\\Giveaway-bot-master\\node_modules\\quick.db\\node_modules\\better-sqlite3\\lib\\binding\\node-v83-win32-x64\\better_sqlite3.node'
  ]
}

**Comment by Zachron-Official** [comment]
I have the same error :P
